CID-2719 - Changes to update user MFA settings to support RACKSPACE_MANDATED
rackerlabs/docs-cloud-identity pull request #138
Opened 2020-11-24 11:14 UTC by abhatt1250

2020-11-24 11:14 UTC, rackernexus commented
Can one of the admins verify this patch?

2020-11-24 13:55 UTC, catlook requested changes
one tweak

2020-11-24 13:55 UTC, catlook commented on api-docs/api-reference/methods/multifactor-auth/put-update-multifactor-settings-on-account-v2.0.rst
> + - Customers need a support ticket if they want to update user's MFA
... update a user's ...

2020-11-24 14:24 UTC, abhatt1250 commented on api-docs/api-reference/methods/multifactor-auth/put-update-multifactor-settings-on-account-v2.0.rst
> + - Customers need a support ticket if they want to update user's MFA
Addressed

2020-11-24 14:26 UTC, catlook approved these changes
👍

2020-11-24 22:23 UTC, premaseem approved these changes

2020-11-30 19:46 UTC, nonameentername approved these changes

2020-12-01 06:57 UTC, merged