CID-2809 - Update public and internal docs to mark API call for customer to set their own API Key as deprecated
rackerlabs/docs-cloud-identity pull request #145
Opened 2021-02-18 18:23 UTC by nonameentername

2021-02-18 18:23 UTC, rackernexus commented
Can one of the admins verify this patch?

2021-02-18 20:10 UTC, catlook requested changes
Couple of suggestions

2021-02-18 20:10 UTC, catlook commented on api-docs/api-reference/methods/users/post-add-credential-to-user-v2.0-users-userid-os-ksadm-credentials.rst
> +    Add api-key credentials to a user is deprecated.
This **Add API-key credentials to a user** operation is deprecated.

2021-02-18 20:10 UTC, catlook commented on api-docs/api-reference/methods/users/post-add-credential-to-user-v2.0-users-userid-os-ksadm-credentials.rst
> +    Please use :ref:`Reset API Key<post-reset-api-key-for-user-v2.0>`
Instead, use :ref:`Reset API Key<post-reset-api-key-for-user-v2.0>`.

2021-02-18 21:35 UTC, catlook approved these changes
👍

2021-02-19 20:35 UTC, kidster approved these changes

2021-02-22 15:44 UTC, merged